server:
  port: 8083
spring:
  datasource:
    url:
    username:
    password:
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create